import type { VisualConfigInput } from "./src/types.js";

const config: VisualConfigInput = {
  baselineUrl: "",
  targetUrl: "",
  outputDir: "visual-test-results",
  urlsFile: "visual/urls.json",
  urlsMarkdownFile: "visual/urls.md",
  pagesFile: "visual/pages.json",
  pagesMarkdownFile: "visual/pages.md",
  urlSource: "crawl",
  sitemapPaths: ["/sitemap.xml", "/sitemap_index.xml"],
  manualPaths: [],
  maxPages: 100,
  threshold: 0.01,
  pixelThreshold: 16,
  retryCount: 1,
  timeoutMs: 30000,
  waitUntil: "networkidle",
  waitForSelector: "",
  fullPage: true,
  allowQuery: false,
  startPath: "/",
  includePathPatterns: ["/**"],
  excludePathPatterns: [
    "/wp-admin/**",
    "/wp-login.php",
    "/login/**",
    "/logout/**",
    "/feed/**",
    "/xmlrpc.php",
    "/wp-json/**",
    "/cart/**",
    "/checkout/**",
  ],
  ignoredExtensions: [
    ".7z",
    ".avi",
    ".css",
    ".doc",
    ".docx",
    ".eot",
    ".gif",
    ".ico",
    ".jpeg",
    ".jpg",
    ".js",
    ".json",
    ".mp3",
    ".mp4",
    ".pdf",
    ".png",
    ".rar",
    ".rss",
    ".svg",
    ".ttf",
    ".txt",
    ".webm",
    ".webp",
    ".woff",
    ".woff2",
    ".xml",
    ".zip",
  ],
  viewports: [
    { name: "desktop", width: 1440, height: 900 },
    { name: "tablet", width: 768, height: 1024 },
    { name: "mobile", width: 390, height: 844 },
  ],
  maskSelectors: ["[data-visual-mask]", ".visual-mask"],
  hideSelectors: [
    "[data-visual-hide]",
    ".grecaptcha-badge",
    "iframe[src*='googletagmanager']",
    "iframe[src*='doubleclick']",
  ],
  cookieBanner: {
    acceptSelectors: [
      "button:has-text('Accept')",
      "button:has-text('I agree')",
      "button:has-text('Allow all')",
      "[aria-label='Accept cookies']",
    ],
    dismissSelectors: [
      "button:has-text('Close')",
      "button:has-text('Dismiss')",
      "[aria-label='Close']",
    ],
  },
};

export default config;
